apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
  labels:
    app: dvwa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
spec:
  selector:
    app: dvwa
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
