apiVersion: v1
kind: Pod
metadata:
  name: dvwa
spec:
  containers:
  - name: dvwa
    image: vulnerables/web-dvwa
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dvwa

