apiVersion: v1
kind: Pod
metadata:
  name: dvwa
  labels:
    app: dvwa
spec:
  containers:
  - name: dvwa
    image: vulnerables/web-dvwa
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
spec:
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
